### ISSUE TITLE
Investigate rostest failures in python 3

### ISSUE THREAD

**Issue by paulbovbel** [locusrobotics/catkin_virtualenv#8]
See https://travis-ci.org/locusrobotics/catkin_virtualenv/jobs/309225972

```
[ROSUNIT] Outputting test results to /root/catkin_ws/build/test_catkin_virtualenv_py3/test_results/test_catkin_virtualenv_py3/rostest-test_virtualenv_script.xml
Traceback (most recent call last):
  File "/root/catkin_ws/src/catkin_virtualenv/test_catkin_virtualenv_py3/test/test_virtualenv_script", line 33, in <module>
    rostest.rosrun('test_catkin_virtualenv', 'test_virtualenv_script', TestVirtualenv, sys.argv)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/__init__.py", line 146, in rosrun
    result = rosunit.create_xml_runner(package, test_name, result_file).run(suite)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 275, in run
    result.print_report(stream, time_taken, out_s, err_s)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 202, in print_report
    stream.write(ET.tostring(self.xml(time_taken, out, err).getroot(), encoding='utf-8', method='xml'))
TypeError: must be str, not bytes
[Testcase: testtest_virtualenv_script_py3] ... ok
```

**Comment by paulbovbel** [comment]
See https://github.com/ros/ros/issues/158

**Comment by paulbovbel** [comment]
This has been fixed (but not released) upstream, closing.
