### ISSUE TITLE
ModuleNotFoundError: No module named 'catkin_pkg'

### ISSUE THREAD

**Issue by phondra-pimot** [locusrobotics/catkin_virtualenv#91]
Hi!
I am trying to use this repo, but I cannot handle some problems.
Namely, when I try to catkin_make workspace I get error:
```shell
[ 25%] Generate virtualenv in /home/piotr/catkin_ws/build/venv
Traceback (most recent call last):
  File "/home/piotr/catkin_ws/src/catkin_virtualenv/catkin_virtualenv/scripts/venv_init", line 24, in <module>
    from catkin_virtualenv.venv import Virtualenv
  File "/home/piotr/catkin_ws/src/catkin_virtualenv/catkin_virtualenv/src/catkin_virtualenv/venv.py", line 33, in <module>
    from .collect_requirements import collect_requirements
  File "/home/piotr/catkin_ws/src/catkin_virtualenv/catkin_virtualenv/src/catkin_virtualenv/collect_requirements.py", line 25, in <module>
    from catkin.find_in_workspaces import find_in_workspaces
  File "/opt/ros/melodic/lib/python2.7/dist-packages/catkin/find_in_workspaces.py", line 39, in <module>
    from catkin_pkg.packages import find_packages
ModuleNotFoundError: No module named 'catkin_pkg'
```
I did not modify package at all.
Full error message: [pastebin](https://pastebin.com/TWJGb9Pb)

Thank you in advance!

**Comment by phondra-pimot** [comment]
rosdep install --from-paths ~/catkin_ws/src --ignore-src
make it happen! :D
